### ISSUE TITLE
Addition of other FeII and Stellar Templates

### ISSUE THREAD

**Issue by rremigio** [remingtonsexton/BADASS3#2]
I am using BADASS for another project where I have to extract [OIII] kinematics from Keck KCWI-Blue data (FWHM ~0.950 A from 4600-5700A).

While the VC04 optical FeII template has been working fine for most purposes, there are some spectra in AGN-dominated spaxels where FeII emission is really strong (e.g. Ark 120/Mrk 1095), and I would like to try using different FeII templates for these bins. I have already tried using the K10 template provided and it seems to consistently return NaNs for the function value during the basinhopping step of the fitting. The K10 template seems to work fine when I use it with the MUSE data I have, which makes me think the issue could be something related to the KCWI resolution/FWHM.

I was wondering if it would be possible to implement some other optical FeII templates, such as the Boroson & Green (1992) template or even the recently published Mrk 493 STIS template in  [Park et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022ApJS..258...38P/abstract). 

In a related fashion, I would also like to know if it would be possible to add some higher-resolution stellar templates.  The default libraries seem to have lower resolutions than KCWI, so I had to manually add in the [X-Shooter Library SSP Models](http://xsl.u-strasbg.fr/page_ssp_all.html), although in a limited capacity (solar metallicity, trimmed to 3800 A - 10000A, and re-binned to a linear scale, since by default the wavelengths are sampled in log10, but the resolution changes between the UV/OPT/IR bands). In principle, would it be possible to use additional libraries in prepare_stellar_templates, even if the templates themselves might not be sampled linearly in wavelength, and/or might have varying resolution?

**Comment by remingtonsexton** [comment]
At the time BADASS only supports the included FeII and stellar templates, but  other template libraries will be considered in future releases.  It is theoretically possible to add these libraries yourself in the same fashion as the current default templates, as long as they are prepared in the format that BADASS expects.  Similarly for the X-Shooter templates, it should be possible to implement these yourself, as long as they are in the format BADASS expects.  The main issues I can see however is that they are not linearly sampled as BADASS only supports templates that are linearly sampled.  The change in resolution also poses a problem.

The issues you have with NaNs in the function value occurs when the convolved template is not the same length as the input spectrum, and is caused by the resolution.  This is an ongoing problem we are trying to mitigate.  NaNs in the basinhopping solution also occurs when there are noise values <= 0, since this will cause your likelihood to be undefined.
________________________________
From: rremigio ***@***.***>
Sent: Wednesday, May 18, 2022 9:20 PM
To: remingtonsexton/BADASS3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [remingtonsexton/BADASS3] Addition of other FeII and Stellar Templates (Issue #2)


I am using BADASS for another project where I have to extract [OIII] kinematics from the Keck KCWI-Blue data (FWHM ~0.950 A from 4600-5700A).

While the VC04 optical FeII template has been working fine for most purposes, there are some spectra in AGN-dominated spaxels where FeII emission is really strong (e.g. Ark 120/Mrk 1095), and I would like to try using different FeII templates for these bins. I have already tried using the K10 template provided and it seems to consistently return NaNs for the function value during the basinhopping step of the fitting. The K10 template seems to work fine when I use it with the MUSE data I have, which makes me think the issue could be something related to the KCWI resolution/FWHM.

I was wondering if it would be possible to implement some other optical FeII templates, such as the widely used Boroson & Green (1992) template or even the recently published Mrk 493 STIS template in Park et al. (2022)<https://secure-web.cisco.com/14zzUXs-sDSTgR0-aED3pd6y1dLWohexEBxqMfDEQpGLX1hhqwi4rnnboh8uEqm_kH-zRckxLVVW3xcNLbmo0vTKChV2oeec1xCiH8_SkVh0ycxqYLDqeS9JQlzLGZ2jQoswbJnm-a26PZIJIz6_X2o0JZ__GEPp-BPyaXoUvFVlNIeosr-_RTLqXsvjEYRJf-Xng07phljoONJQRHN9uVq7NCrUkjNhfzgzYn8YUnB30f2NoecpBfgkTBcRtl5NvnOijwU0w7uX-SVKl65eTBnVJJVh_Qyp1MzPLnD0kfrkduUoVlIIeu6uHibbWvX_JIQusP1MJPR40uApCW5HM6PPNnMtsSFHx27_MKxCfFhMrjv1-XvEyau0Y7eytiScm-K46TSlSTZbtzvFylvqqlZ0Kn6LA6gf0-qsIUrgAEY1b0fVXQcgCePhPkXg5uL2mkjwidweYWaj8_FnJSSVFTg/https%3A%2F%2Fui.adsabs.harvard.edu%2Fabs%2F2022ApJS..258...38P%2Fabstract>.

In a related fashion, I would also like to know if it would be possible to add some higher-resolution stellar templates. The default libraries seem to have lower resolutions than KCWI, so I had to manually add in the X-Shooter Library SSP Models<http://secure-web.cisco.com/1EApHf8In8dnZSQ3miGK4lBAPh7uzCphB8T6bZnJgvTtKAsFNjF_c8evx4OAAUHTf2d2Z-xYIkoosHA3Ud91hbK7ECKrM-7kcXvnf8H4LULEWhCIuFzwWz62aPxrGeahrCfeqHbJ75kDbV3ZMVc4oNWyR04mKqafOmNZ-agiUijtSdzsVr-gX0QcYMkYXBwuvOfTu_ENofU2Lg8OhbWO6Cx1EC2M6W6plOR4XshrFkt0Ur9GQX6K8ssZ-YLAqJL3--kf3TRb1DWEuqEj99WyaJeQYB5BtxXezIMPSt0tEtpUq0RJ6QxoksJ5V0HPl0qxqL4MeeJNbjqm8-KIy7Iynzsg1-sIBJ7UVEAcjUC6s600qXuparxoADyiDNbhH7_YY4y8gL5nKaAEpAY7ZlOC-MhH_K92ZauS_nhxHYoKseo4FBwpv5mnJBRl24KnnnTVY/http%3A%2F%2Fxsl.u-strasbg.fr%2Fpage_ssp_all.html>, although in a limited capacity (solar metallicity, trimmed from 3800 A - 10000A, and re-binned to a linear scale, since by default the wavelengths are sampled in log10, b! ut the resolution changes between the UV/OPT/IR bands). In principle, would it be possible to use additional libraries in prepare_stellar_templates, even if the templates themselves might not be sampled linearly in wavelength, and/or might have varying resolution?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1VQdcq-qd6AW0HHUz_tpapu0wtT81--n1mICOVpFomj4QEE9ebScbbNKY1z00yWdB-NdIH5ML6Q_ktERZF6-3JD2za64od0r5JwMFTJInKXPnxQ-FLWzPpLG6hpgCmNYHsMJZxV0tbT9cY72LUAlfZFkoeR6BB2fPCLgr9M2wcV6UXPvwyAuJaPFCLrUlssiGwe2OL5vYO7ejCgIeP1doI4-qzmDuJO2H44IuGBSYkOkrAdDuOOxBvYEBV5KwfIad-42fcks2cZCOP6ypAVXJ16pDyKrguXuSqVXYdio3O9lhlt6wsWHoGP_MYlzfJwsQnE07KJ5g-c-hL_8NCyi9raSwSfENzev9OGpnAN7o5uaBQS9FP9zT5rJlSddZXaz27j7IezE-hL7ONr95bT9bOUl8vDS4pOgIJzwat72L287RstguiV7kPpcoNME6d48B/https%3A%2F%2Fgithub.com%2Fremingtonsexton%2FBADASS3%2Fissues%2F2>, or unsubscribe<https://secure-web.cisco.com/15Dlz5w8LQkHtE1JsCZhrPsEKsg0ENlCUt_uAG7cNaJZ-zfMDAFV7fkGXdbLZDVkLdPI3GAzfy_PsSRUhGsmBpWuPiM1QdW40oUIgo4ZO1i2FHqxVlo0JUcHD5xbxMylyzh6aJ4F8UMumanTVvcGgoGXw5ZBTy5dYZDdC_vVmxAx80gP_PKXe56U081E4todAvtVMx_9SUrC2g2J2BaWn5xqODndH0VMbgrgnCrd9tt4R5iRPfhlNdcQhA2bQt5Cek!
%20zNrUmFsLc3Jna5xe17TMtKufzMkfZm1lfi0MnFwVjxM34aciM64gKrbTMEAvPKykqAgxGxaiDYD1ypxmftiWkxBL6KDz-O5HZ33XwQVycA2PQtmcyHaqsIeWMabwj7lVT0qSNsrxFJR7_2AKME8zicMmPSsjHvl20DsrWYHbVv2h5AItM2BEpbddTsxWo4-/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF7IPQHXFTLPAHVH5CQDEPLVKWJMZANCNFSM5WKJPRDQ>.

**Comment by rremigio** [comment]
I ended up inputting the [Maraston and Stromback (2011)](https://ui.adsabs.harvard.edu/abs/2011MNRAS.418.2785M/abstract) templates based on ELODIE (FWHM = 0.55 A, linearly sampled), which was simple. 

Also was able to successfully implement Mrk 493 STIS template by adding blocks of code similar to the Veron-Cetty template (but without the need to separate broad an narrow Fe II).
