### ISSUE TITLE
Clarification of Vacuum vs Air Wavelengths in BADASS

### ISSUE THREAD

**Issue by rremigio** [remingtonsexton/BADASS3#3]
Forgive me for making a third post, but I would like to know if BADASS assumes the user-input spectrum is in vacuum or air wavelengths. The stellar template libraries included with BADASS seem to be in air wavelengths, but the "default" emission line lists are at vacuum wavelengths (no idea about the VC04 or K10 FeII templates), and I have not successfully found anything in the code that mentions a conversion or preference between the two. 

I would think that if the default stellar libraries are used for to fit for the LOSVD (e.g. IndoUS for MUSE data), then it would be helpful to have an indication that air wavelengths are assumed.

**Comment by remingtonsexton** [comment]
BADASS makes no assumptions on the user-input spectrum, since the user must provide the correct redshift to perform the fit in the spectrum's rest frame.  All velocities are measured with respect to the redshift corrected frame.  Emission line wavelengths are defined using the SDSS definitions found here: http://classic.sdss.org/dr6/algorithms/linestable.html, which are in vacuum.  The Fe II template lines are defined from their bibliographical sources, and empirical stellar libraries, are all assumed to be defined in the rest frame and have vacuum wavelengths.
Table of Spectral Lines Used in SDSS<http://classic.sdss.org/dr6/algorithms/linestable.html>
Table of Spectral Lines Used in SDSS REFERENCE WAVELENGTHS, IN VACUUM, USED IN SPECTRO1D
classic.sdss.org

________________________________
From: rremigio ***@***.***>
Sent: Friday, May 20, 2022 4:12 AM
To: remingtonsexton/BADASS3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [remingtonsexton/BADASS3] Clarification of Vacuum vs Air Wavelengths in BADASS (Issue #3)


Forgive me for making a third post, but I would like to know if BADASS assumes the user-input spectrum is in vacuum or air wavelengths. The stellar template libraries included with BADASS seem to be in air wavelengths, but the "default" emission line lists are at vacuum wavelengths (no idea about the VC04 or K10 FeII templates), and I have not successfully found anything in the code that mentions a conversion or preference between the two.

I would think that if the default stellar libraries are used for to fit for the LOSVD (e.g. IndoUS for MUSE data), then it would be helpful to have an indication that air wavelengths are assumed.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1L192PmfyisXm95gimVO57REnJtBZIF8yE6Yvrs9Wxzg9J43-FVNGZGejNxE-Sf1XQXXXlZenWSnx9CQMsMFWlTKwPliqta-KeXRJYhkj2s70wJbrBcm3qNbv3LV37vbzpc1Ch6MhPB3qx52LUR2k4j2wSV-O0S-7rL8fkPoMjCUJnTx1x_BSd-4IYU8WAMnZNEfs-t2Z5tTjrq4jHtFF1CFtr0v0llu0EfpUVWdskAYT2CGC20m7ilHltoYHHgnDaqDdUoINr8P8qBFy7uGODGROffpqhfFgZC1m7gdkwjsE7i61wtxoLkS1ppki_43K1okLBCvRdcSITnR7NNCXdaqssn0opcqfb3hPea_A9vBTCdFBF-XquaAiY-CWYi5MGtuAAXGV6IzPAGziVEFr19VykY5OXez-lpMvE48U-W300tRXiNSVwiIKGbtUJrXi/https%3A%2F%2Fgithub.com%2Fremingtonsexton%2FBADASS3%2Fissues%2F3>, or unsubscribe<https://secure-web.cisco.com/1YpdMzlgFVM4JO01L_YB7fbQZ8UTOs8qduat7jHntqur1NCkZVaJToof4EGrd-cB1JTbM1NOmpl6QE8Eni0h_tg6EXIWbWgi1gR448Wo8BXG09J3O9lxB2bcX8IEzxKgHgfTaOVTr8w10NWD4mWJl-J88BFpPMVEO49RB926uZggkydjqt9uAZT4aam5VxGdSNCa52-zMw4pz_zVp51CT1QqLxl_aVhBQPT2rQQy2s_NADUdc45ML3r3yWYdzwcilE!
%202hZwoRN0ViGhyV5W1vXB8YGykAsFoUwyga6GjWGgPzgHXtl_N6O5n7XjzjcD44tuMV1xW1m5kbGofnWmk-rTYw9d7ZqYoidFsdXX2DfQ0BqzroB23pvJkSYTBwt-OO3R2Nn-oOatXIqjBUB46jSuxnzaXI5BxsDvs_Guz1wDmMqqHZFaIDf8o8Z-Gaq8S69/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF7IPQGMXJZGGNURHN2EJ2LVK5CNNANCNFSM5WOUXWAQ>.

**Comment by rremigio** [comment]
I have tried looking at the spectra from the IndoUS, Vazdekis, and eMILES spectra provided with BADASS, and have plotted the locations of Balmer lines (red for air wavelengths, white for vacuum wavelengths obtained from the SDSS line table). At least for the eMILES and Vazdekis spectra, the air wavelengths seem to be closer to where the minimums of the absorption lines are. This would make me think that if obtaining stellar kinematics is important, air wavelengths should be used for this part of BADASS.

![badass_stellar_hbeta](https://user-images.githubusercontent.com/42788999/169605799-4a093ab1-9286-4a98-97a4-3cadd48822ea.png)
 
![badass_stellar_library](https://user-images.githubusercontent.com/42788999/169605352-7df131b0-779f-4877-bd87-206732625e2b.png)

![badass_stellar_halpha](https://user-images.githubusercontent.com/42788999/169605889-50bb4d6a-1a84-40d8-9a04-bfa6e3539b70.png)

**Comment by rremigio** [comment]
I have gotten the best results on my stellar kinematics maps by assuming air wavelengths. Using vacuum wavelengths introduced a ~100 km/s offset between the two BADASS runs, where the central spaxels were not close to zero velocity, even when simple disk rotation was expected.
